# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: projet cicd flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Nettoyer le cache Maven
      run: rm -rf /home/runner/.m2/repository/org/sonarsource/scanner/maven

    - name: Build with Maven and SonarQube Scan
      run: mvn clean install sonar:sonar \
          -Dsonar.projectKey=cicd \
          -Dsonar.organization=com.example \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: abdou008/springboot-images-new
          tags: V1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Nettoyer les fichiers temporaires
      run: rm -rf /home/runner/work/_temp/*
#    - name: SonarQube Scan
#      uses: SonarSource/sonarqube-scan-action@v1 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
#      with:
#        projectBaseDir:
#        args: >
#          -Dsonar.organizat=com.example
#          -Dsonar.projectKey=cicd
#      env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # name: Update dependency graph
     # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
